version: 2.1
jobs:
  build:
    docker:
      - image: klakegg/hugo:busybox
    steps:
      - checkout
      - run: git submodule sync;
      - run: git submodule update --init
      - run: hugo -D;
      - run: ls -la