version: 2.1
jobs:
  prep:
    docker:
        - image: alpine/git
    steps: 
      - checkout
      - run: git submodule sync;
      - run: git submodule update --init
      - save_cache:
           key: my-cache
           paths:
             - /
  build:
    docker:
      - image: klakegg/hugo:busybox
    steps:
      - restore_cache:
            key: my-cache
      - run: ls -la
      - run: hugo -D;

workflows:
    version: 2
    workflow:
        jobs:
            - prep
            - build:
                requires:
                    - prep